### ISSUE TITLE
Ingeniería del Prompting (cont.)

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#21]
Una vez obtenido el prompt sencillo ahora queda ir explicando los siguientes pasos de manera evolutiva, comprobando como va mejorando el resultado obtenido por parte del LLM, hasta obtener el resultado que queremos obtener que pueda ser pasado a la aplicación móvil:
-JSON que contenga los POI de manera estructurada.

**Comment by fps1001** [comment]
Se ha intentado obtener información haciendo scraping de Tripadvisor, al existir una API de pago (aunque es gratis hasta 5.000 peticiones al mes) se paraliza este avance hasta hablar con @clopezno pues puede incumplir los Terminos de Servicio. Avanzaré usando Wikivoyage mientras.

**Comment by clopezno** [comment]
Continua con Wikivoyage y comenta la decisón de rechazar tripadvisor en las sección de aspectos relevantes de la memoria Latex del TFG.
