### ISSUE TITLE
Revisión documentación memoria v0.2

### ISSUE THREAD

**Issue by clopezno** [fps1001/TFGII_FPisot#42]
Adjunto pdf con los comentarios de revisión. 
Espero que se entiendan y puedan servir para mejorar la comprensión del TFG.
[memoria-5_revclopezno.pdf](https://github.com/user-attachments/files/17032989/memoria-5_revclopezno.pdf)

**Comment by fps1001** [comment]
➤ Hay que cuidar las referencias: 
- Hay que añadir referencias bibliográficas en el texto, i.e: 3.1 GIS.
- Incluir referencias a secciones y a figuras (Ver.Fig. x)
- Hacer referencia al código usado visualizandolo como "code" también se puede incluir referencia url al prototipo del cuaderno.

➤ Usar una forma impersonal y en presente: "se pasa".
➤ Imprimir glosario de acrónimos.
➤ Documentar últimos sprints en el anexo correspondiente.

**Comment by fps1001** [comment]
Estilo:
➤ Cuidado con el uso de : en exceso.
➤ No usar frases muy largas con estructura compleja.
➤ Enumeraciones deben tener un cierre que no sea etc.

**Comment by fps1001** [comment]
Añado un ejemplo de uso de bloc sencillo de la aplicación.
