### ISSUE TITLE
Reorganización de proyecto: Clase Eco City Tour a nuevo Bloc

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#46]
Surge la necesidad de guardar la información de los servicios de LLM y Places en un mismo gestor de estados.
Creo que guardar toda la información en un bloc puede ser una buena idea que facilite la labor a la hora de compartir la información en las pantallas y los servicios, reduciendo las peticiones y haciendo más fácil labores posteriores como la eliminación de un POI o guardar los ecocitytours. 
Al haber expandido tanto el proyecto se generará una rama para comprobar el funcionamiento.

**Comment by fps1001** [comment]
Flujo Deseado:
En TourSelectionScreen, cuando el usuario selecciona las opciones y pulsa un botón:
- Se debe hacer la petición a GeminiService para obtener los puntos de interés (POIs).
- Una vez obtenidos los POIs, se actualizan con información adicional usando PlacesService.
- Después de mejorar los POIs, se crea una ruta optimizada que una los POIs usando OptimizationService.
- Cuando los datos estén listos (POIs + ruta optimizada), se navega a MapScreen y se muestra el mapa con la ruta y los marcadores.

Todo ello con las clases EcoCityTour y PointOfInterest centrando la lógica en vez de numerosas clases y para operar con ellos TourBloc accesible desde todos los lugares de la aplicación.

**Comment by clopezno** [comment]
Una buena descripción del diseño del flujo de actividades y su relación con los componentes. Esta información la tendremos que modelar con diagramas de actividad UML y de componentes para añadirla al anexo de diseño.
