### ISSUE TITLE
Límite a la extensión del Eco City Tour

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#48]
Se busca la manera de límitar que el LLM indique POIs demasiado lejos entre sí.
La idea inicial es añadir un widget que limite por tiempo o distancia el tour y que o bien el LLM o bien el sistema de optimización lo tengan en cuenta a la hora de generar un Eco City Tour.

**Comment by fps1001** [comment]
Se probará primero a hacerlo con el prompt del LLM para ver su fiabilidad antes de consumir peticiones al servicio de optimización.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/d9f990ebecc6e2c6af4139c864bb7070-image.png) 


Recorrido para media hora máximo de naturaleza por Burgos. --> No funciona bien limitar por LLM. Aunque si noto que cambia las preferencias, si no puede cumplirlas las ignora completamente, habría que probar con distancia u otra manera de pedirlo, porque aún creo que puede funcionar.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/c4ddb3ff9a96e175149bf0ce48559056-image.png)
Palo Alto, 60 minutos andando. Bien.
![image.png](https://zube.io/files/proyectos-fpisot/e84bfc543916d2bc2b11b61252226af9-image.png)
Burgos, 30 minutos andando. Bien.
![image.png](https://zube.io/files/proyectos-fpisot/30bb965ec6183856480483183033c019-image.png)
Burgos, 3 horas máximo en bici. Bien. Elige una ruta mucho más grande, aunque no llegue a ocupar todo el tiempo pues es un límite máximo. Lo tiene en cuenta.
Hay que revisar el servicio de optimización pues 80 km/h en bici es irreal.

**Comment by clopezno** [comment]
Buen trabajo! Los lugares de interés de la ruta resultante me parecen muy interesantes, pero en la descripción de los lugares de interés aparecen alucinaciones. Huerta del rey vs. jardín botánico.  Arco de San Esteban vs. un jardín histórico. ¿Se te ocurre algo en el servicio de optimización para poder controlar las alucinaciones?

**Comment by fps1001** [comment]
La API de Places no tiene un campo que sea descripción, se podría usar algún comentario de algún visitante o recurrir a la API de wikipedia, lo pruebo y te indico resultados.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/180693f8059254b4570540926374bf30-image.png) ![image.png](https://zube.io/files/proyectos-fpisot/2b216832efb68f7b51800a0e5411528c-image.png)
Se podrá usar este sistema siempre que haya una entrada exacta del POI. Lo implemento a ver qué te parece.

**Comment by fps1001** [comment]
Solo wikipedia o wikivoyage generan descripción de los servicios que he mirado tienen un campo descripción sin embargo la busqueda tiene que ser exacta, con lo que rara vez se actualiza el campo.

**Comment by fps1001** [comment]
Creo que la solución pasa por utilizar un modelo mejor. He cambiado el modelo de gemini 1.5-flash a 1.5-pro. También volví a cambiar el prompt. La conclusión es que tarda un poco más en generar la ruta pero creo que afina más el recorrido y las descripciones tienen más que ver con el rol_prompting del guía turístico:
![image.png](https://zube.io/files/proyectos-fpisot/85672c8f47f06d2bcee293819cce0818-image.png) 
Tour < 1 hora.

**Comment by clopezno** [comment]
De acuerdo con tu propuesta solución. Me parece muy interesante el proceso de decisión que has seguido.  Lo documentaría en otra issue en la sección de aspectos relevantes de la memoria. Posible subtítulo Puntos de interés con LLM: alucinaciones y optimizaciones de rutas turísticas.
