### ISSUE TITLE
Determinar ODS implicado/s

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#5]
Hay que determinar a qué ODS's se ajusta mejor el proyecto y enfocarlo en ellos.

**Comment by clopezno** [comment]
Enlazo un par de referencias bibliográficas por si  sirven  para definir e integrar los ODS en el TFG


https://aenui.org/actas/fichas/JENUI_2024_031.html
@inproceedings{key,
	AUTHOR = "Markiegi, Urtzi;Aldalur, Iñigo",
	TITLE = "Abordando los Objetivos de Desarrollo Sostenible en el Aprendizaje Basado en Problemas universitario",
	BOOKTITLE = "Actas de las JENUI - Vol. 9 (2024)",
	YEAR = 2024,
	PAGES = "251 -- 254",
	ADDRESS = "La Coruña",
	MONTH = "jun",
} 


https://aenui.org/actas/pdf/JENUI_2023_031.pdf
@inproceedings{key,
	AUTHOR = "Markiegi,Urtzi;Aldalur,Iñigo;Perez,Alain",
	TITLE = "Integrando los ODS en el grado de Ingeniería Informática",
	BOOKTITLE = "Actas de las JENUI - Vol. 8 (2023)",
	YEAR = 2023,
	PAGES = "249 -- 256",
	ADDRESS = "Granada",
	MONTH = "jul",
}

**Comment by fps1001** [comment]
En el informe https://uis.unesco.org/sites/default/files/documents/sdg_11_synthesis_report_2023_v11_0_4.pdf  se explica el poder multiplicador de este ODS, que creo es el que mejor aúna las ventajas de una aplicación como la que se va a desarrollar.

**Comment by fps1001** [comment]
Además del ODS11, el concepto de **smart city** aunque sobreutilizado por el marketing de empresas que usa soluciones de este tipo, se alinea perfectamente con el TFG:  "utiliza diferentes tipos de sensores electrónicos y tecnologías de información y comunicación (TIC) para *recopilar datos*. Esta información se utiliza para gestionar activos y recursos de manera eficiente, mejorando la calidad de vida de los habitantes. Las smart cities *buscan optimizar operaciones en áreas como el transporte*, la energía, el saneamiento, la seguridad y otros servicios públicos, a través de su integración."

**Comment by fps1001** [comment]
Se determina usar el ODS11 centrándose ya que tiene la función de influir en los otros ODS. Se mencionará la aplicación como uso de smart city.
Se intentará explicar también en la memoria la utilidad de aplicar trabajos con ODS en la enseñanza. (aporte @clopezno )
Se intentará unir la problemática del turismo actual con el ODS para la documentación de la memoria.
