### ISSUE TITLE
Diagramas de paquetes/componentes

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#50]
Se buscará la manera de generar estos diagramas de manera automática a través de paquetes de flutter, y sino se realizarán de manera tradicional con draw.io.

**Comment by fps1001** [comment]
Este paquete de dart convierte el código a un documento que después se puede usar en PlantUML:
https://pub.dev/packages/dcdg

**Comment by fps1001** [comment]
dart pub global run dcdg -o diagramasUML 
esto genera un archivo de texto que se puede copiar en https://www.plantuml.com/plantuml/uml/
documentación del paquete: https://pub.dev/documentation/dcdg/latest/

**Comment by fps1001** [comment]
![nLjVS-Ce4d_tfr3vwQxcvZw0QohUIURFpktC9XLdRXzLM6hRx23G0Kh6kxVV_VWZR8GLLTn3SY-9rGtDxzT0qo3qaz94wgvXCmMwuAG1rP8ALj0IIRIGnM8ncrMCA5NCMob-XqgNf6qNYpKJbLeijgt_KzhdVzR6rcBniLMNvcbU_3ahYjShBO4qgswjAabRJGL_K.png](https://zube.io/files/proyectos-fpisot/16a7f74355e5e42161ede23b574077ba-nljvs-ce4d_tfr3vwqxcvzw0qohuiurfpktc9xldrxzlm6hrx23g0kh6kxvv_vwzr8glltn3sy-9rgtdxzt0qo3qaz94wgvxcmmwuag1rp8alj0iirignm8ncrmca5ncmob-xqgnf6qnypkjbleijgt_kzhdvzr6rcbnilmnvcbu_3ahyjshbo4qgswjaabrjgl_k.png)

**Comment by fps1001** [comment]
![Mesa de trabajo 1.png](https://zube.io/files/proyectos-fpisot/5e5b8acac00e49c90a48dcd5b27f7783-mesa-de-trabajo-1.png)![diagrama de componentes.svg](https://zube.io/files/proyectos-fpisot/7dee76cc180a2fef9585c0b9457ff15b-diagrama-de-componentes.svg)

**Comment by clopezno** [comment]
Además de esta vista completa de los paquetes con sus clases y relaciones,  se necesita una vista simplificada donde solo aparezcan los paquetes sin sus clases y solos con las dependencias entre paquetes. 
El diagrama de componentes, para modelar el diseño los servicios que usa la aplicación, habrá que hacerlo directamente desde  PlantUML https://plantuml.com/es/component-diagram

**Comment by fps1001** [comment]
![diagrama_servicios.png](https://zube.io/files/proyectos-fpisot/cff12743143cf2c73de6da61542bc5a3-diagrama_servicios.png)![diagrama_componentes.png](https://zube.io/files/proyectos-fpisot/1d54754fa76e752e819615484fd0711c-diagrama_componentes.png)

**Comment by fps1001** [comment]
Se instala la extensión drawio para vscode y genero los diagramas pedidos. Creo varios para comentarlos en el sprint review, también hay que tener en cuenta que pueden sufrir variaciones.![components-simple.png](https://zube.io/files/proyectos-fpisot/15a1586b3fea3f99897c71d16c565bbe-components-simple.png)![diagrama-casos-de-uso.png](https://zube.io/files/proyectos-fpisot/afb4c03fac404280cd6ec76403036709-diagrama-casos-de-uso.png)![entidad-relacion.png](https://zube.io/files/proyectos-fpisot/97fa04956cf7ccb61c2ba05b68e94fbf-entidad-relacion.png)![components-diagram.png](https://zube.io/files/proyectos-fpisot/8bca6217f8df6577acb8161f8e1135c6-components-diagram.png)

**Comment by clopezno** [comment]
Necesitamos revisar la notación UML: visibilidad atributos, tipos de relaciones entre elementos, multiplicidad de relaciones.
 El último diagrama, al añadir nombres de funciones a las relaciones creo que se modelaría mejor con un diagrama de secuencia. Son detalles de notación fácilmente solucionables,  dejamos pendiente de revisar en la siguiente reunión.
