### ISSUE TITLE
Convocatoria Prototipos Orientados al Mercado 

### ISSUE THREAD

**Issue by clopezno** [fps1001/TFGII_FPisot#55]
Por si interesa buscar financiación adjunto convocatoria con el formulario
https://www.ubu.es/te-interesa/convocatoria-prototipos-orientados-al-mercado-curso-2024-2025

La evaluación  pueda servir para validar el interés externo de la aplicación.

**Comment by fps1001** [comment]
Incluyo solicitud para revisión por parte de @clopezno si lo cree conveniente.[formulario_solicitud_convocatoria_prototipos_24-25_0.docx](https://zube.io/files/proyectos-fpisot/3bcdc26cc09ddd608327f6eedff592dc-formulario_solicitud_convocatoria_prototipos_24-25_0.docx)

**Comment by clopezno** [comment]
Adjunto una nueva versión. He ampliado el contenido de las secciones 3.5 y 3.9.[Protipo_EcocityTour_V02.docx](https://zube.io/files/proyectos-fpisot/3c91b00a1c3fcfe4899a1266af9e9da7-protipo_ecocitytour_v02.docx)

**Comment by fps1001** [comment]
Enviada solicitud.
