### ISSUE TITLE
Configurar tarea de despliegue continuo Flutter/Dart con actions de Github -> apk

### ISSUE THREAD

**Issue by clopezno** [fps1001/TFGII_FPisot#56]
Consultar 
https://medium.com/@colonal/automating-flutter-builds-and-releases-with-github-actions-77ccf4a1ccdd

**Comment by fps1001** [comment]
Consultado con el experto David Miguel: "El problema de usar .env para API keys es que se puede extraer del fichero de instalación de la app, por lo que te las pueden robar. Si las ofuscas lo dificultas un poco más, pero no lo mitigas. Lo única solución real es o usar un proxy que añade la header de autenticación o utilizar algo como VertexAI for Firebase que está protegido con App Check.
Pero bueno, igual para el TFG no hay que hilar tan fino. Lo puedes poner como mejoras futuras"
Lo vemos el martes 22.

**Comment by fps1001** [comment]
De manera análoga al test con github secrets se puede pasar las apis e intentar hacer la automatización creando un .env temporal mientras se construye el apk
[despliegue continuo. explicación con github secrets.pdf](https://zube.io/files/proyectos-fpisot/d3d5d74144456289f409c2f0604a6e89-despliegue-continuo-explicacion-con-github-secrets.pdf)

**Comment by fps1001** [comment]
La automatización de crear la apk falló, aún así se incluye en la carpeta de workflows sin activar. 
Se realizó manualmente como en las pre-releases anteriores la v0.4
