### ISSUE TITLE
Guardar Eco City Tour

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#57]
Se requiere que se pueda guardar un tour creado por el usuario.
Se valoran varias opciones entre usar gestión directa de json, IsarDB o alguna solución de Google.
De igual manera debería cargar, exportar e importar dicha estructura idealmente a un archivo json.

**Comment by fps1001** [comment]
Firestore contectada a aplicación y colección y documentos conectados a base de datos. Guardado exitoso:
![image.png](https://zube.io/files/proyectos-fpisot/851a5c180b8d00d814f2a1bad86235e0-image.png)

**Comment by fps1001** [comment]
Falta generar tourbloc si carga una ruta al inicio sin generar tour e identificar las rutas guardadas por un usuario para que no salgan todas las de la base de datos sino las que identifique al usuario. Quizá haya que hacer una autentificación anónima para identificar al usuario sin loguearse. Funcionalidad esta de loguearse que quizá haya que plantearse en otro sprint...(quizá fuese necesario para monetizar la aplicación y sería fácil con firebase acoplado al proyecto).

**Comment by fps1001** [comment]
Ya identifica al usuario anónimamente y guarda sus propios tours.
El único caso especial en esta configuración sería que el usuario al reinstalar la aplicación generaría otro UserId y por tanto no vería sus antiguos tours cargados. (seguirían existiendo en firebase).

**Comment by clopezno** [comment]
Sin problema. Se documenta la mejora en la sección de líneas de trabajo futuras de la memoria. Buen trabajo.
