### ISSUE TITLE
Corrección de diagramas

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#58]
Corrección de los diagramas según las instrucciones recibidas:
- Diagrama de clases en vez de entidades con notación UML.
- Casos de uso por pantalla, más agrupados en las descripciones.
- Los servicios de Google deben figurar como actores en los diagramas.

**Comment by fps1001** [comment]
![diagrama-casos-de-uso.png](https://zube.io/files/proyectos-fpisot/0d65349ac32c9d30e9e050d5883b53db-diagrama-casos-de-uso.png)
Más alineado con lo que sugería @clopezno. Hay que modificar los CU de la documentación para adaptarlo a este nuevo diagrama.

**Comment by clopezno** [comment]
Creo que esta nueva propuesta expresa mejor los casos de uso de Eco City Tour. Buen trabajo.

Un par de comentarios menores por si sirve para mejorar la comprensión. En los casos se uso utilizas el término "Eco City Tour" para referirte a una "ruta turísticas" compuesta por varios "puntos de interés turístico POI".  Tu opción me parece correcta, pero puede mejorar la comprensión del mismo si se añade  una nota UML en el diagrama para asociar estos conceptos sinónimos.

Cambiaría el nombre "Seleccionar Eco ... " "Calcular Eco...". En ese caso de uso incluiría además  un nuevo caso de uso para la configuración de parámetros de la ruta.

Por último añadiría un nuevo actor usuario Admin Eco City que interactuaría con el registro de log.
Recuerda definir además de los casos de uso los actores.

**Comment by fps1001** [comment]
Nueva versión con las indicaciones de @clopezno  ![casos_de_usos.png](https://zube.io/files/proyectos-fpisot/8d75b4bd2de2ed2e3b5c7182ddbb0356-casos_de_usos.png)

**Comment by fps1001** [comment]
Clases con plantUML: ![clases.png](https://zube.io/files/proyectos-fpisot/f154414e295418734a14f5164277acbf-clases.png)
Versión abreviada: ![clases_drawio.png](https://zube.io/files/proyectos-fpisot/59570712bcba41cd2b52a74086f557f0-clases_drawio.png)

**Comment by clopezno** [comment]
Una pequeña cuestión de notación que se me había pasado. Si numeras los casos de uso puede ayudarte a documentarlos y a ganar comprensión.  Sugiero esta numeración CU01 Configuración de parámetros Eco city tour, CU02 Navegar Mapa, CU03 Ver resumen Eco city tour, CU04 Guardar EcocityTour, CU05 Cargar Ecocity, CU06 Registro de Log. La enumeración de los <<include>> al pertenecer a un solo caso de uso puedes anidar CU01.1 Calcular tour, CU01.2 Obtener POI...

Otra cuestión menor es que las la navegabilidad de las asociaciones a los actores y casos de uso la diseñaría bidireccional, es decir eliminar la flecha.

Respecto a la nueva versión simplificada  del diagrama de clases mejora su comprensión.  Hay algunos detalles que hay que mejorar. Las clase PointofInterest, EcocityTour y GoogleController tienen un definido el método por defecto (method(type):type). 
Puede ser interesante visualizar el nombre del paquete junto al nombre de la clases.

**Comment by fps1001** [comment]
Actualización con las últimas indicaciones.
![casos-de-uso.png](https://zube.io/files/proyectos-fpisot/8a99ffbc5d2579d7153c8f6af1d13553-casos-de-uso.png)![clases.png](https://zube.io/files/proyectos-fpisot/bf1d9393129b580d459e1947bae6402f-clases.png) En la issue #59 se intentará cuadrar la información de actores y casos de uso lo que igual repercute en algún diagrama, pero en principio quedan así.
