### ISSUE TITLE
Tests de aplicación / Cobertura

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#62]
Se requiere conectar con sonarcloud en local o automáticamente de tal manera que se identifique la cobertura.
La cobertura de los tests debe ser de un nivel que garantice la calidad del código.
Para realizar los test con garantías se necesita un manejo amplio de las clases de test: Mock y de paquetes Mockito o Mocktail.

**Comment by fps1001** [comment]
Sigo sin conseguir que se detecte la cobertura @clopezno El archivo de cobertura existe pero no lo interpreta el scaner. Estoy empezando a pensar que la versión del scanner es incompatible con la cobertura de flutter/dart. Voy a intentar probar sonarqube en local.

**Comment by clopezno** [comment]
He buscado en sonarcloud.io proyectos desarrollados con dart para comprobar si alguno tenía la cobertura activada. He encontrado un tutorial de integración de sonar cloud con flutter y con la cobertura activa. Analizando el fichero donde se describe el workflow en github actions si que parece importante la versión del Sonar_scanner utilizada. En concreto en el ejemplo se trabaja con   SONAR_SCANNER_VERSION=6.2.1.4610.

Puede ser interesante que clones el ejemplo y pruebes si puedes se calcula la cobertura en Sonarcloud correctamente. Si funciona podrás ajustar la configuración en tu repositorio.

Te paso las direcciones del repositorio y de un artículo divulgativo.

https://github.com/AlexKriatov/sonarcloud_flutter_tutorial/actions/runs/11224160347/workflow
https://medium.com/@oleksandr.kriatov/automated-code-analysis-for-flutter-integrating-sonarcloud-with-github-actions-e82cfe951620

**Comment by fps1001** [comment]
"Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows." Importante lo que pone Alex aquí, que la ruta es relativa al archivo de propiedades.![image.png](https://zube.io/files/proyectos-fpisot/9e74251a6427eb1500480c0bcfdd572b-image.png)
Se hace un fork del proyecto, se configura el repositorio y sonarcloud y se comprueba que existe integración completa, sin errores y **marcando cobertura**. Se llevará esta configuración al repositorio principal: tanto de versión del scaner, yaml y properties.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/08183ad7854d7faaba761f6aca74c844-image.png) Workflow funcionando y con esta versión del scanner ya marca la cobertura (aunque sea poca).

**Comment by clopezno** [comment]
¡Buen trabajo Fernando!
