### ISSUE TITLE
Refinamiento final de prompting

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#67]
Se busca mejorar la experiencia de usuario al buscar POIs en ubicaciones pequeñas: el comportamiento actual te dirige a capitales de provincia cercanas o el recorrido es extremadamente largo.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/a6753826f7c6e74f4a818fb697220278-image.png) 
"Ten en cuenta el tipo de cliente al que le ofreces información y los siguientes intereses del usuario: ${userPreferences.join(', ')}.  
El recorrido debe hacerse en menos de 2 horas. Prioriza lugares que estén cerca del lugar de inicio. 
Si algún punto está a más de 10 km. de cualquier otro, no lo incluyas en la lista."

Estoy encontrando mejores resultados al pedirle que excluya los lejanos al punto de origen. El tiempo de ruta me estoy pensando en eliminarlo. 

Quizá se podría poner la distancia en vez del tiempo, para pedirle que descarte a los que están a más de x km. Pudiendo así poner por ejemplo a la gente que quiera ir en bici, rutas más largas, o quien quiera andar en una ciudad tramos más pequeños de 1 km. por ejemplo.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/00b4408d538ebd3f0db8cef072b936c9-image.png)
Tengo un problema con nombres de sitios que se llaman igual. Google Places actualiza las coordenadas por el nombre que elige Gemini y a veces se va a otro monumento que se llama igual...

**Comment by clopezno** [comment]
Quizás si añades se añade a la petición a Google Places el lugar que introduce el usuario + el lugar de Gemini se consigue resolver la ambigüedad semántica.
