### ISSUE TITLE
Test: gestor de estados Bloc

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#69]
Se busca generar más cobertura general al incluir los gestores de estados presentes en gran parte de la aplicación. Se plantea usar menos mocks y más elementos reales que se puedan crear o usar técnicas de happy path que demuestren el resultado esperado de la interacción con la aplicación.

**Comment by fps1001** [comment]
https://bloclibrary.dev/testing/ https://www.ics.com/blog/how-conduct-unit-tests-using-bloc

**Comment by clopezno** [comment]
Me parece muy interesante el artículo. En el apéndice de  diseño y arquitectura creo que es muy interesante que documentes el patrón de diseño Bloc utilizando las ideas del artículo https://www.ics.com/blog/building-flutter-discover-bloc-pattern. Tu arquitectura depende claramente de este patrón.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/39b6edef399fb0a0b21da346f3f640ae-image.png) 
Va a ser difícil superar esto.
