### ISSUE TITLE
Revisión final memoria

### ISSUE THREAD

**Issue by clopezno** [fps1001/TFGII_FPisot#72]
Adjunto un pdf con comentarios de la última revisión de la memoria. Además, proporciono unos comentarios generales

Comentarios de revisión menores basados en formato 
- Cambiar formato de referencias \cite{} por ~\cite{} para añadir un espacio con el texto.
- Revisar que la cita al final del texto esté   después del punto ".[3]" vs [3]
- Revisar la calidad y el fondo de las imágenes pare impresión
- Palabras en inglés en cursiva. Esto puede incluir Eco City Tours.
- Hacer una última pasada del corrector sintáctico: turístico, imágenes etc..
- Referencias en el texto  a Figuras en lugar de imágenes
- Acrónimos.La primera aparición en el texto de contenido del acrónimo se pone el término y entre paréntesis la sigla o acrónimo. Está bien aplicado en el resumen pero no en la introducción. Los  plurales de los acrónimos en español no varían ej: los PC. La "s" final se añade en inglés.
- Cuidado con la utilización de comillas en Latex   

Otros comentarios de revisión:
- Incluir las prácticas de agilidad de integración continua (testing y compilación)  y calidad continua  en conceptos teóricos relacionados con sprint review. 
Se puede incluir las actions definidas en técnicas y herramientas con alguna captura de pantalla de SonarQA.
- Falta por terminar la sección de conclusiones
- Hay un problema en la generación del índice de las secciones del documento. Tiene que haber un problema con Latex y las etiquetas de las subsecciones o las referencias a los nombres de ficheros.
- En aspectos relevantes puedes comentar la importancias de la autoformación y tu comunicación con un profesional de Flutter como David. Además del hecho de tomar como referencia su TFG para yu autoformar. 
Habrá que incluirle de alguna forma en agradecimientos. 
[memoria-9.pdf](https://github.com/user-attachments/files/17917124/memoria-9.pdf)

**Comment by fps1001** [comment]
@clopezno Revisión completada. Añadido conclusiones, integración continua, Sonar y mención a David.
