### ISSUE TITLE
Internacionalización

### ISSUE THREAD

**Issue by fps1001** [fps1001/TFGII_FPisot#74]
Se estudia la posibilidad de internacionalizar la aplicación.
Hay que estudiar cómo hacerlo y llevarlo a cabo. Especialmente en el caso del prompt del modelo.

**Comment by fps1001** [comment]
Se decide probar con el paquete: https://pub.dev/packages/easy_localization sobre intl.

**Comment by fps1001** [comment]
![image.png](https://zube.io/files/proyectos-fpisot/daa77509f0978b5a86c0bdb82814f410-image.png)
Instalación de internacionalización funcionando.

**Comment by clopezno** [comment]
El cambio de selección de idiomas se suele hacer con las banderas del país, con esto se facilita la comprensión y a acceso a la funcionalidad de internacionalización . Imagina que la aplicación arranca en chino y pone "所選語言為中文"  
;-)

**Comment by fps1001** [comment]
Estaba probando la integración de todas las piezas que componen la internacionalización.
He modificado el diseño teniendo en cuenta lo que comentas y cambiado la carga de tours a un botón inferior para no saturar la barra y porque creo que se entiende mejor así. Espero quede más claro así.
![image.png](https://zube.io/files/proyectos-fpisot/6546a1067b29552cb1ab7bc0718dc87b-image.png) 
![image.png](https://zube.io/files/proyectos-fpisot/be5975956212fcd05aedd81e1ba52801-image.png)
![image.png](https://zube.io/files/proyectos-fpisot/ac49ad595df40abfd89b9e57906b5841-image.png)
