### ISSUE TITLE
Revisión Anexo: planifición y análisis

### ISSUE THREAD

**Issue by clopezno** [fps1001/TFGII_FPisot#81]
Adjunto pdf con comentarios  de revisión menores 
[anexos-1_revclopezno.pdf](https://github.com/user-attachments/files/18195379/anexos-1_revclopezno.pdf)

**Comment by fps1001** [comment]
Añado notas de la review:
- Faltan dos blocs en el diagrama de clases, explicarlo.
- Arquitectónico sobre procedimental.
- Eco City Tour a glosario enlazado a nota de diagrama de caso de uso (Figura B.2)
- Cuidado con el término "Preferencias de usuario".
- Licencia nominativo: mi nombre debe aparecer en la licencia.
- Implements en el diagrama de paquetes y un paquete por encima de dataset y repository que sea Persistence_bd (refactorizar en código).

**Comment by fps1001** [comment]
Se modifica "preferencias de usuario" a "propiedades de configuración de la ruta", que creo elimina la ambigüedad y explica mejor qué son.

**Comment by fps1001** [comment]
Se decide añadir los blocs faltantes al diagrama de clases.
